// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAywGAoSS5nBurlTxMMd_A8p4gI0OikqRo',
    appId: '1:730009823039:web:37d379e319e084c5fcd58a',
    messagingSenderId: '730009823039',
    projectId: 'roomdecorarfyp',
    authDomain: 'roomdecorarfyp.firebaseapp.com',
    storageBucket: 'roomdecorarfyp.appspot.com',
    measurementId: 'G-CQB2RQWLP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtpRO79UkdlnQySHBvdo4HQx7Fk-qr5eI',
    appId: '1:730009823039:android:8ccd173e60ca67eefcd58a',
    messagingSenderId: '730009823039',
    projectId: 'roomdecorarfyp',
    storageBucket: 'roomdecorarfyp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKbqk4w5d7ZTzVH2PEznz3J0fOr6VWO30',
    appId: '1:730009823039:ios:fbc803f3adc8e832fcd58a',
    messagingSenderId: '730009823039',
    projectId: 'roomdecorarfyp',
    storageBucket: 'roomdecorarfyp.appspot.com',
    iosBundleId: 'com.example.roomdecorar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKbqk4w5d7ZTzVH2PEznz3J0fOr6VWO30',
    appId: '1:730009823039:ios:0432d1f466dff405fcd58a',
    messagingSenderId: '730009823039',
    projectId: 'roomdecorarfyp',
    storageBucket: 'roomdecorarfyp.appspot.com',
    iosBundleId: 'com.example.roomdecorar.RunnerTests',
  );
}
