// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCarriaBiURPxuoKY_ulZT_OGrUOcOCV9o',
    appId: '1:431924738418:web:e2e552404ee84fddc985eb',
    messagingSenderId: '431924738418',
    projectId: 'roomdecordatabase-43368',
    authDomain: 'roomdecordatabase-43368.firebaseapp.com',
    storageBucket: 'roomdecordatabase-43368.appspot.com',
    measurementId: 'G-F9CDGJ32GW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT4q_xskKfJYRnbw-YnkQw16vAkuDaFDE',
    appId: '1:431924738418:android:a9c37ff008742eb8c985eb',
    messagingSenderId: '431924738418',
    projectId: 'roomdecordatabase-43368',
    storageBucket: 'roomdecordatabase-43368.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZMaMr3HTqc4sTsBtRHtrHavJhCgQssCs',
    appId: '1:431924738418:ios:372399436f398960c985eb',
    messagingSenderId: '431924738418',
    projectId: 'roomdecordatabase-43368',
    storageBucket: 'roomdecordatabase-43368.appspot.com',
    iosBundleId: 'com.example.roomdecorar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZMaMr3HTqc4sTsBtRHtrHavJhCgQssCs',
    appId: '1:431924738418:ios:1d9cabd004f9907fc985eb',
    messagingSenderId: '431924738418',
    projectId: 'roomdecordatabase-43368',
    storageBucket: 'roomdecordatabase-43368.appspot.com',
    iosBundleId: 'com.example.roomdecorar.RunnerTests',
  );
}
